trigger:
- master

variables:
  system.debug: true
  SYSTEM_ACCESSTOKEN: $(System.AccessToken)

jobs:
- job: BuildOnWindows
  displayName: "Build and test on Windows"
  pool:
    name: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: PowerShell@2
    inputs:
      filePath: "scripts/corpus-ci.ps1"